// SPDX-License-Identifier: AGPL-3.0-only

package plugins

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"unicode"

	"github.com/iamdoubz/lasterp/kernel/plugins/abi"
)

// `lasterp plugin bindings` (WP-3.2b): typed Go structs for the objects a
// tenant actually has.
//
// The input is `GET /api/v1/meta/objects` — the surface that is already
// per-tenant and already capability-filtered, so a plugin author generates
// against the schema their tenant runs rather than against whatever this
// repository's modules happen to declare. It is also the surface that gains
// custom fields when WP-3.2c lands overlays, which is the entire reason typed
// bindings are worth generating at all.
//
// **Go only** (WP-3.2-decisions.md §6). §5 argues that a scaffold CI cannot
// compile is a template rather than a proof; a generator whose output nothing
// type-checks is that argument with fewer excuses, since generated code is
// exactly where drift shows up last. Go's output is compiled by the test suite.

// MetaObject is one object from the metadata endpoint. Only the fields the
// generator needs are declared — an endpoint that grows a key should not break
// a code generator.
type MetaObject struct {
	Name string `json:"name"`
	// Module and Persistence come straight from the endpoint. Persistence
	// matters to an author: an event-sourced object has no CRUD surface, so a
	// host call cannot create one.
	Module      string      `json:"module"`
	Persistence string      `json:"persistence"`
	Fields      []MetaField `json:"fields"`
}

// MetaField is one field of an object.
type MetaField struct {
	Name     string   `json:"name"`
	Type     string   `json:"type"`
	Required bool     `json:"required"`
	Options  []string `json:"options"`
}

// GenerateGoBindings renders a Go source file of structs for these objects.
//
// The generated struct is a *record* type, not an API client: a plugin reads
// and writes records through the host functions as JSON, so what an author is
// missing is the shape and the field names, and that is all this emits.
func GenerateGoBindings(pkg string, objects []MetaObject) ([]byte, error) {
	if pkg == "" {
		pkg = "main"
	}
	sort.Slice(objects, func(i, j int) bool { return objects[i].Name < objects[j].Name })

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by "lasterp plugin bindings"; DO NOT EDIT.
//
// These types mirror the effective schema of the tenant they were generated
// against — base objects plus that tenant's own customisations. Regenerate
// after a schema change; a stale binding is how a plugin starts writing a field
// that no longer exists.
//
// Generated against ABI %s.

package %s

`, abi.Version, pkg)

	if usesMoney(objects) {
		b.WriteString("// Money is an amount in an ISO-4217 currency's minor units — cents, not\n" +
			"// a float. Every money value in LastERP has this shape, in a plugin as much\n" +
			"// as in the server: a float somewhere in a money path is how a ledger stops\n" +
			"// balancing.\ntype Money struct {\n" +
			"\tMinorUnits int64 `json:\"minor_units\"`\n" +
			"\tCurrency   string `json:\"currency\"`\n}\n\n")
	}

	for _, o := range objects {
		fmt.Fprintf(&b, "// %s is the %s object (module %s, %s persistence).\n",
			goName(o.Name), o.Name, o.Module, o.Persistence)
		fmt.Fprintf(&b, "type %s struct {\n", goName(o.Name))
		// Every record carries these, whatever the object declares.
		b.WriteString("\tID        string `json:\"id,omitempty\"`\n")
		b.WriteString("\tCreatedAt string `json:\"created_at,omitempty\"`\n")
		b.WriteString("\tUpdatedAt string `json:\"updated_at,omitempty\"`\n")
		for _, f := range o.Fields {
			comment := ""
			if f.Required {
				comment = " // required"
			}
			if len(f.Options) > 0 {
				comment += " // one of: " + strings.Join(f.Options, ", ")
			}
			fmt.Fprintf(&b, "\t%s %s `json:%q`%s\n", goName(f.Name), goType(f.Type), f.Name+",omitempty", comment)
		}
		b.WriteString("}\n\n")

		// The object name as a constant, so a host call cannot be misspelled in
		// a string literal — which is the one mistake typed bindings should be
		// able to prevent for an author writing JSON by hand.
		fmt.Fprintf(&b, "// Object%s is the name to pass as \"object\" in a host call.\nconst Object%s = %q\n\n",
			goName(o.Name), goName(o.Name), o.Name)
	}

	src, err := format.Source(b.Bytes())
	if err != nil {
		// Returning the unformatted source alongside the error would hand the
		// author a file that does not compile; better to fail loudly here,
		// where the generator can be fixed.
		return nil, fmt.Errorf("plugins: generated bindings do not parse: %w", err)
	}
	return src, nil
}

// ParseMetaObjects reads the metadata endpoint's `{"data": [...]}` envelope.
func ParseMetaObjects(body []byte) ([]MetaObject, error) {
	var envelope struct {
		Data []MetaObject `json:"data"`
	}
	if err := json.Unmarshal(body, &envelope); err != nil {
		return nil, fmt.Errorf("plugins: metadata response is not JSON: %w", err)
	}
	return envelope.Data, nil
}

func usesMoney(objects []MetaObject) bool {
	for _, o := range objects {
		for _, f := range o.Fields {
			if f.Type == "money" {
				return true
			}
		}
	}
	return false
}

// goType maps a metadata field type to the Go type a JSON record decodes into.
//
// Money is deliberately **not** a float and not a bare int: it is minor units
// plus a currency, and the generated struct says so, because commandment "money
// is integer minor units + ISO-4217" applies to a plugin author's code exactly
// as it applies to ours.
func goType(fieldType string) string {
	switch fieldType {
	case "int", "integer":
		return "int64"
	case "bool", "boolean":
		return "bool"
	case "money":
		return "Money"
	default:
		// text, email, enum, date, datetime, reference: all JSON strings on the
		// wire, and a plugin that wants a time.Time can parse one.
		return "string"
	}
}

// goName turns `invoice_number` or `Invoice` into `InvoiceNumber`.
func goName(s string) string {
	var out strings.Builder
	upper := true
	for _, r := range s {
		switch {
		case r == '_' || r == '-' || r == '.' || r == ' ':
			upper = true
		case upper:
			out.WriteRune(unicode.ToUpper(r))
			upper = false
		default:
			out.WriteRune(r)
		}
	}
	name := out.String()
	// Go's own initialisms, so `id` does not become `Id` in a file people read.
	for _, fix := range []struct{ from, to string }{{"Id", "ID"}, {"Url", "URL"}, {"Api", "API"}} {
		if name == fix.from {
			return fix.to
		}
		if strings.HasSuffix(name, fix.from) {
			return strings.TrimSuffix(name, fix.from) + fix.to
		}
	}
	return name
}
